version: '3.7'

services:

    webclient:
        container_name: 'webclient'
        image: webclient
        logging:
            driver: 'json-file'
            options:
                max-size: '1024k'
                max-file: '10'
        ports:
            - '80:80'

    webservice:
        container_name: 'webservice'
        image: webservice
        logging:
            driver: 'json-file'
            options:
                max-size: '1024k'
                max-file: '10'

    config:
        container_name: 'config'
        image: config-server
        logging:
            driver: 'json-file'
            options:
                max-size: '1024k'
                max-file: '10'
