FROM maven:3.6.2-jdk-11 AS maven
WORKDIR /opt/src
COPY ./ /opt/src/
RUN mvn clean && mvn package

FROM openjdk:8u201-jdk-alpine3.9 AS base
WORKDIR /opt/src
RUN apk add --no-cache curl \
    && mkdir -p /opt/src/target /opt/src/main

FROM base
COPY --from=maven /opt/src/target/main.jar /opt/src/target
COPY ./src/main/resources /opt/src/main/resources
CMD ["java", "-jar", "target/main.jar", "--spring.config.location=file:///opt/src/main/resources/bootstrap.yml"]

